apiVersion: v1
kind: ConfigMap
metadata:
  name: alertmanager-config
  namespace:
  labels:
    app.kubernetes.io/name: alertmanager
    app.kubernetes.io/instance: monitoring
data:
  alertmanager.yml: |
    global:
      resolve_timeout: 5m

    route:
      receiver: webhook-receiver
      group_wait: 10s
      group_interval: 30s
      repeat_interval: 1h

    receivers:
    - name: webhook-receiver
      webhook_configs:
      - url: "http://remediator:5001/remediate"

