apiVersion: apps/v1
kind: Deployment
metadata:
  name: shnms
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shnms
  template:
    metadata:
      labels:
        app: shnms
    spec:
      containers:
      - name: shnms
        image: jaspreet1388/shnms-api:latest 
        ports:
        - containerPort: 8000
        securityContext:
          capabilities:
            add: ["NET_ADMIN"]
---
apiVersion: v1
kind: Service
metadata:
  name: shnms-service
spec:
  selector:
    app: shnms
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8000
  type: LoadBalancer

