apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: latency-alert-rule
  namespace: 
  labels:
    release: monitoring
spec:
  groups:
  - name: shnms.rules
    rules:
    - alert: HighLatencyDetected
      expr: histogram_quantile(0.9, rate(http_request_duration_seconds_bucket[1m])) > 0.7
      for: 1m
      labels:
        severity: critical
      annotations:
        summary: "High latency detected in SHNMS service"

